name: Nginx website workflow

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup onboardbase
        id: fetch-secrets
        uses: Onboardbase/onboardbase-action@v0.0.8
        with:
          apikey: ${{secrets.ONBOARDBASE_APIKEY}}
          passcode: ${{secrets.ONBOARDBASE_PASSCODE}}
          project: test
          environment: development

      - name: Test onboardbase
        run: ${{ steps.fetch-secrets.outputs.MYSELF }}

      - name: Build an image from Dockerfile
        run: |
          docker build -t nginx-website .
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'nginx-website'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.IMAGE_TAG }}:latest
